# Use the official CSP plugin in ENFORCING mode
[[plugins]]
package = "@netlify/plugin-csp"

  # Plugin inputs: define policies per path
  [plugins.inputs]
  reportOnly = false

  # ---- Global policy (applies to all pages) ----
  [[plugins.inputs.policies]]
  path = "/*"
    [plugins.inputs.policies.directives]
    defaultSrc = ["'self'"]
    # You use inline JS and styles in your site; allow them.
    scriptSrc  = ["'self'", "'unsafe-inline'", "https://identity.netlify.com", "https://unpkg.com", "https://cdn.jsdelivr.net"]
    styleSrc   = ["'self'", "'unsafe-inline'"]
    # CMS and identity make XHR/fetch calls to these hosts
    connectSrc = ["'self'", "https://identity.netlify.com", "https://api.netlify.com", "https://unpkg.com", "https://cdn.jsdelivr.net"]
    imgSrc     = ["'self'", "data:", "blob:"]
    fontSrc    = ["'self'", "data:"]
    # Identity opens in an embedded frame during auth
    frameSrc   = ["https://identity.netlify.com"]

  # ---- Admin policy (Netlify CMS) ----
  # CMS bundles can eval() in devtools and some widgets; allow 'unsafe-eval' here only.
  [[plugins.inputs.policies]]
  path = "/admin/*"
    [plugins.inputs.policies.directives]
    defaultSrc = ["'self'"]
    scriptSrc  = ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://identity.netlify.com", "https://unpkg.com", "https://cdn.jsdelivr.net"]
    styleSrc   = ["'self'", "'unsafe-inline'"]
    connectSrc = ["'self'", "https://identity.netlify.com", "https://api.netlify.com", "https://unpkg.com", "https://cdn.jsdelivr.net"]
    imgSrc     = ["'self'", "data:", "blob:"]
    fontSrc    = ["'self'", "data:"]
    frameSrc   = ["https://identity.netlify.com"]
